from back_end.config import get_settings as _get_settings, settings


APP_TITLE = settings.APP_TITLE
APP_VERSION = settings.APP_VERSION
APP_DESCRIPTION = settings.APP_DESCRIPTION
APP_HOST = settings.APP_HOST
APP_PORT = settings.APP_PORT
MONGO_URL = settings.MONGO_URL
DB_NAME = settings.DB_NAME
JWT_SECRET = settings.JWT_SECRET
JWT_ALGORITHM = settings.JWT_ALGORITHM
ENVIRONMENT = settings.ENVIRONMENT
ACCESS_TOKEN_EXPIRE_DAYS = settings.ACCESS_TOKEN_EXPIRE_DAYS
CORS_ORIGINS = settings.CORS_ORIGINS
INITIAL_SUPER_ADMIN_NAME = settings.INITIAL_SUPER_ADMIN_NAME
INITIAL_SUPER_ADMIN_EMAIL = settings.INITIAL_SUPER_ADMIN_EMAIL
INITIAL_SUPER_ADMIN_PASSWORD = settings.INITIAL_SUPER_ADMIN_PASSWORD

MONGODB_URI = MONGO_URL
MONGODB_DB_NAME = DB_NAME
JWT_SECRET_KEY = JWT_SECRET


def get_settings():
    return _get_settings()
